/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthControllerGetStravaAuthUrl200Response
 */
export interface AuthControllerGetStravaAuthUrl200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerGetStravaAuthUrl200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the AuthControllerGetStravaAuthUrl200Response interface.
 */
export function instanceOfAuthControllerGetStravaAuthUrl200Response(value: object): value is AuthControllerGetStravaAuthUrl200Response {
    return true;
}

export function AuthControllerGetStravaAuthUrl200ResponseFromJSON(json: any): AuthControllerGetStravaAuthUrl200Response {
    return AuthControllerGetStravaAuthUrl200ResponseFromJSONTyped(json, false);
}

export function AuthControllerGetStravaAuthUrl200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthControllerGetStravaAuthUrl200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function AuthControllerGetStravaAuthUrl200ResponseToJSON(json: any): AuthControllerGetStravaAuthUrl200Response {
    return AuthControllerGetStravaAuthUrl200ResponseToJSONTyped(json, false);
}

export function AuthControllerGetStravaAuthUrl200ResponseToJSONTyped(value?: AuthControllerGetStravaAuthUrl200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

