/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutBlockDto } from './WorkoutBlockDto';
import {
    WorkoutBlockDtoFromJSON,
    WorkoutBlockDtoFromJSONTyped,
    WorkoutBlockDtoToJSON,
    WorkoutBlockDtoToJSONTyped,
} from './WorkoutBlockDto';

/**
 * 
 * @export
 * @interface CreateWorkoutDto
 */
export interface CreateWorkoutDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutDto
     */
    date: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutDto
     */
    trainingPlanId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutDto
     */
    weeklyGoalId?: string;
    /**
     * 
     * @type {CreateWorkoutDtoSportTypeEnum}
     * @memberof CreateWorkoutDto
     */
    sportType: CreateWorkoutDtoSportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkoutDto
     */
    description?: string;
    /**
     * 
     * @type {Array<WorkoutBlockDto>}
     * @memberof CreateWorkoutDto
     */
    blocks?: Array<WorkoutBlockDto>;
    /**
     * 
     * @type {CreateWorkoutDtoStatusEnum}
     * @memberof CreateWorkoutDto
     */
    status: CreateWorkoutDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkoutDto
     */
    intensity?: number;
}


/**
 * @export
 */
export const CreateWorkoutDtoSportTypeEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type CreateWorkoutDtoSportTypeEnum = typeof CreateWorkoutDtoSportTypeEnum[keyof typeof CreateWorkoutDtoSportTypeEnum];

/**
 * @export
 */
export const CreateWorkoutDtoStatusEnum = {
    Scheduled: 'scheduled',
    Done: 'done',
    Skipped: 'skipped',
    Partial: 'partial'
} as const;
export type CreateWorkoutDtoStatusEnum = typeof CreateWorkoutDtoStatusEnum[keyof typeof CreateWorkoutDtoStatusEnum];


/**
 * Check if a given object implements the CreateWorkoutDto interface.
 */
export function instanceOfCreateWorkoutDto(value: object): value is CreateWorkoutDto {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('trainingPlanId' in value) || value['trainingPlanId'] === undefined) return false;
    if (!('sportType' in value) || value['sportType'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateWorkoutDtoFromJSON(json: any): CreateWorkoutDto {
    return CreateWorkoutDtoFromJSONTyped(json, false);
}

export function CreateWorkoutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkoutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'trainingPlanId': json['trainingPlanId'],
        'weeklyGoalId': json['weeklyGoalId'] == null ? undefined : json['weeklyGoalId'],
        'sportType': json['sportType'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(WorkoutBlockDtoFromJSON)),
        'status': json['status'],
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
    };
}

export function CreateWorkoutDtoToJSON(json: any): CreateWorkoutDto {
    return CreateWorkoutDtoToJSONTyped(json, false);
}

export function CreateWorkoutDtoToJSONTyped(value?: CreateWorkoutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'trainingPlanId': value['trainingPlanId'],
        'weeklyGoalId': value['weeklyGoalId'],
        'sportType': value['sportType'],
        'title': value['title'],
        'description': value['description'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(WorkoutBlockDtoToJSON)),
        'status': value['status'],
        'intensity': value['intensity'],
    };
}

