/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWeeklyGoalDto
 */
export interface CreateWeeklyGoalDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWeeklyGoalDto
     */
    trainingPlanId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeeklyGoalDto
     */
    weekStartDate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWeeklyGoalDto
     */
    weekEndDate: string;
    /**
     * 
     * @type {object}
     * @memberof CreateWeeklyGoalDto
     */
    metrics?: object;
}

/**
 * Check if a given object implements the CreateWeeklyGoalDto interface.
 */
export function instanceOfCreateWeeklyGoalDto(value: object): value is CreateWeeklyGoalDto {
    if (!('trainingPlanId' in value) || value['trainingPlanId'] === undefined) return false;
    if (!('weekStartDate' in value) || value['weekStartDate'] === undefined) return false;
    if (!('weekEndDate' in value) || value['weekEndDate'] === undefined) return false;
    return true;
}

export function CreateWeeklyGoalDtoFromJSON(json: any): CreateWeeklyGoalDto {
    return CreateWeeklyGoalDtoFromJSONTyped(json, false);
}

export function CreateWeeklyGoalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWeeklyGoalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trainingPlanId': json['trainingPlanId'],
        'weekStartDate': json['weekStartDate'],
        'weekEndDate': json['weekEndDate'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
    };
}

export function CreateWeeklyGoalDtoToJSON(json: any): CreateWeeklyGoalDto {
    return CreateWeeklyGoalDtoToJSONTyped(json, false);
}

export function CreateWeeklyGoalDtoToJSONTyped(value?: CreateWeeklyGoalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trainingPlanId': value['trainingPlanId'],
        'weekStartDate': value['weekStartDate'],
        'weekEndDate': value['weekEndDate'],
        'metrics': value['metrics'],
    };
}

