/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEquipmentDto
 */
export interface CreateEquipmentDto {
    /**
     * 
     * @type {string}
     * @memberof CreateEquipmentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEquipmentDto
     */
    imagePath: string;
}

/**
 * Check if a given object implements the CreateEquipmentDto interface.
 */
export function instanceOfCreateEquipmentDto(value: object): value is CreateEquipmentDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('imagePath' in value) || value['imagePath'] === undefined) return false;
    return true;
}

export function CreateEquipmentDtoFromJSON(json: any): CreateEquipmentDto {
    return CreateEquipmentDtoFromJSONTyped(json, false);
}

export function CreateEquipmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEquipmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'imagePath': json['imagePath'],
    };
}

export function CreateEquipmentDtoToJSON(json: any): CreateEquipmentDto {
    return CreateEquipmentDtoToJSONTyped(json, false);
}

export function CreateEquipmentDtoToJSONTyped(value?: CreateEquipmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'imagePath': value['imagePath'],
    };
}

