/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTrainingPlanDto
 */
export interface CreateTrainingPlanDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanDto
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanDto
     */
    objective: string;
    /**
     * 
     * @type {CreateTrainingPlanDtoStatusEnum}
     * @memberof CreateTrainingPlanDto
     */
    status: CreateTrainingPlanDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTrainingPlanDto
     */
    targetDate?: string;
    /**
     * 
     * @type {Array<CreateTrainingPlanDtoSportsEnum>}
     * @memberof CreateTrainingPlanDto
     */
    sports: Array<CreateTrainingPlanDtoSportsEnum>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTrainingPlanDto
     */
    autoGenerate?: boolean;
}


/**
 * @export
 */
export const CreateTrainingPlanDtoStatusEnum = {
    Active: 'ACTIVE',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED',
    Locked: 'LOCKED',
    Draft: 'DRAFT'
} as const;
export type CreateTrainingPlanDtoStatusEnum = typeof CreateTrainingPlanDtoStatusEnum[keyof typeof CreateTrainingPlanDtoStatusEnum];

/**
 * @export
 */
export const CreateTrainingPlanDtoSportsEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type CreateTrainingPlanDtoSportsEnum = typeof CreateTrainingPlanDtoSportsEnum[keyof typeof CreateTrainingPlanDtoSportsEnum];


/**
 * Check if a given object implements the CreateTrainingPlanDto interface.
 */
export function instanceOfCreateTrainingPlanDto(value: object): value is CreateTrainingPlanDto {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('objective' in value) || value['objective'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sports' in value) || value['sports'] === undefined) return false;
    return true;
}

export function CreateTrainingPlanDtoFromJSON(json: any): CreateTrainingPlanDto {
    return CreateTrainingPlanDtoFromJSONTyped(json, false);
}

export function CreateTrainingPlanDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTrainingPlanDto {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'],
        'objective': json['objective'],
        'status': json['status'],
        'targetDate': json['targetDate'] == null ? undefined : json['targetDate'],
        'sports': json['sports'],
        'autoGenerate': json['autoGenerate'] == null ? undefined : json['autoGenerate'],
    };
}

export function CreateTrainingPlanDtoToJSON(json: any): CreateTrainingPlanDto {
    return CreateTrainingPlanDtoToJSONTyped(json, false);
}

export function CreateTrainingPlanDtoToJSONTyped(value?: CreateTrainingPlanDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'objective': value['objective'],
        'status': value['status'],
        'targetDate': value['targetDate'],
        'sports': value['sports'],
        'autoGenerate': value['autoGenerate'],
    };
}

