/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanNextWeekDto
 */
export interface PlanNextWeekDto {
    /**
     * 
     * @type {number}
     * @memberof PlanNextWeekDto
     */
    numberOfRuns?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanNextWeekDto
     */
    weekStartDate?: string;
}

/**
 * Check if a given object implements the PlanNextWeekDto interface.
 */
export function instanceOfPlanNextWeekDto(value: object): value is PlanNextWeekDto {
    return true;
}

export function PlanNextWeekDtoFromJSON(json: any): PlanNextWeekDto {
    return PlanNextWeekDtoFromJSONTyped(json, false);
}

export function PlanNextWeekDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanNextWeekDto {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfRuns': json['numberOfRuns'] == null ? undefined : json['numberOfRuns'],
        'weekStartDate': json['weekStartDate'] == null ? undefined : json['weekStartDate'],
    };
}

export function PlanNextWeekDtoToJSON(json: any): PlanNextWeekDto {
    return PlanNextWeekDtoToJSONTyped(json, false);
}

export function PlanNextWeekDtoToJSONTyped(value?: PlanNextWeekDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfRuns': value['numberOfRuns'],
        'weekStartDate': value['weekStartDate'],
    };
}

