/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterUserDto
 */
export interface RegisterUserDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterUserDto
     */
    dateOfBirth: string;
    /**
     * 
     * @type {number}
     * @memberof RegisterUserDto
     */
    weight: number;
    /**
     * 
     * @type {number}
     * @memberof RegisterUserDto
     */
    height: number;
}

/**
 * Check if a given object implements the RegisterUserDto interface.
 */
export function instanceOfRegisterUserDto(value: object): value is RegisterUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function RegisterUserDtoFromJSON(json: any): RegisterUserDto {
    return RegisterUserDtoFromJSONTyped(json, false);
}

export function RegisterUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'userName': json['userName'],
        'name': json['name'],
        'password': json['password'],
        'confirmPassword': json['confirmPassword'],
        'dateOfBirth': json['dateOfBirth'],
        'weight': json['weight'],
        'height': json['height'],
    };
}

export function RegisterUserDtoToJSON(json: any): RegisterUserDto {
    return RegisterUserDtoToJSONTyped(json, false);
}

export function RegisterUserDtoToJSONTyped(value?: RegisterUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'userName': value['userName'],
        'name': value['name'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
        'dateOfBirth': value['dateOfBirth'],
        'weight': value['weight'],
        'height': value['height'],
    };
}

