/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StravaCallbackDto
 */
export interface StravaCallbackDto {
    /**
     * 
     * @type {string}
     * @memberof StravaCallbackDto
     */
    code: string;
}

/**
 * Check if a given object implements the StravaCallbackDto interface.
 */
export function instanceOfStravaCallbackDto(value: object): value is StravaCallbackDto {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function StravaCallbackDtoFromJSON(json: any): StravaCallbackDto {
    return StravaCallbackDtoFromJSONTyped(json, false);
}

export function StravaCallbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StravaCallbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function StravaCallbackDtoToJSON(json: any): StravaCallbackDto {
    return StravaCallbackDtoToJSONTyped(json, false);
}

export function StravaCallbackDtoToJSONTyped(value?: StravaCallbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

