/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitWorkoutFeedbackDto
 */
export interface SubmitWorkoutFeedbackDto {
    /**
     * 
     * @type {boolean}
     * @memberof SubmitWorkoutFeedbackDto
     */
    completed: boolean;
    /**
     * 
     * @type {number}
     * @memberof SubmitWorkoutFeedbackDto
     */
    effort: number;
    /**
     * 
     * @type {number}
     * @memberof SubmitWorkoutFeedbackDto
     */
    fatigue: number;
}

/**
 * Check if a given object implements the SubmitWorkoutFeedbackDto interface.
 */
export function instanceOfSubmitWorkoutFeedbackDto(value: object): value is SubmitWorkoutFeedbackDto {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('effort' in value) || value['effort'] === undefined) return false;
    if (!('fatigue' in value) || value['fatigue'] === undefined) return false;
    return true;
}

export function SubmitWorkoutFeedbackDtoFromJSON(json: any): SubmitWorkoutFeedbackDto {
    return SubmitWorkoutFeedbackDtoFromJSONTyped(json, false);
}

export function SubmitWorkoutFeedbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitWorkoutFeedbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
        'effort': json['effort'],
        'fatigue': json['fatigue'],
    };
}

export function SubmitWorkoutFeedbackDtoToJSON(json: any): SubmitWorkoutFeedbackDto {
    return SubmitWorkoutFeedbackDtoToJSONTyped(json, false);
}

export function SubmitWorkoutFeedbackDtoToJSONTyped(value?: SubmitWorkoutFeedbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'effort': value['effort'],
        'fatigue': value['fatigue'],
    };
}

