/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateEquipmentDto
 */
export interface UpdateEquipmentDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEquipmentDto
     */
    imagePath?: string;
}

/**
 * Check if a given object implements the UpdateEquipmentDto interface.
 */
export function instanceOfUpdateEquipmentDto(value: object): value is UpdateEquipmentDto {
    return true;
}

export function UpdateEquipmentDtoFromJSON(json: any): UpdateEquipmentDto {
    return UpdateEquipmentDtoFromJSONTyped(json, false);
}

export function UpdateEquipmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEquipmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'imagePath': json['imagePath'] == null ? undefined : json['imagePath'],
    };
}

export function UpdateEquipmentDtoToJSON(json: any): UpdateEquipmentDto {
    return UpdateEquipmentDtoToJSONTyped(json, false);
}

export function UpdateEquipmentDtoToJSONTyped(value?: UpdateEquipmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'imagePath': value['imagePath'],
    };
}

