/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutBlockDto } from './WorkoutBlockDto';
import {
    WorkoutBlockDtoFromJSON,
    WorkoutBlockDtoFromJSONTyped,
    WorkoutBlockDtoToJSON,
    WorkoutBlockDtoToJSONTyped,
} from './WorkoutBlockDto';

/**
 * 
 * @export
 * @interface UpdateWorkoutDto
 */
export interface UpdateWorkoutDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutDto
     */
    description?: string;
    /**
     * 
     * @type {Array<WorkoutBlockDto>}
     * @memberof UpdateWorkoutDto
     */
    blocks?: Array<WorkoutBlockDto>;
    /**
     * 
     * @type {number}
     * @memberof UpdateWorkoutDto
     */
    intensity?: number;
    /**
     * 
     * @type {UpdateWorkoutDtoStatusEnum}
     * @memberof UpdateWorkoutDto
     */
    status?: UpdateWorkoutDtoStatusEnum;
    /**
     * 
     * @type {UpdateWorkoutDtoSportTypeEnum}
     * @memberof UpdateWorkoutDto
     */
    sportType?: UpdateWorkoutDtoSportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkoutDto
     */
    date?: string;
}


/**
 * @export
 */
export const UpdateWorkoutDtoStatusEnum = {
    Scheduled: 'scheduled',
    Done: 'done',
    Skipped: 'skipped',
    Partial: 'partial'
} as const;
export type UpdateWorkoutDtoStatusEnum = typeof UpdateWorkoutDtoStatusEnum[keyof typeof UpdateWorkoutDtoStatusEnum];

/**
 * @export
 */
export const UpdateWorkoutDtoSportTypeEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type UpdateWorkoutDtoSportTypeEnum = typeof UpdateWorkoutDtoSportTypeEnum[keyof typeof UpdateWorkoutDtoSportTypeEnum];


/**
 * Check if a given object implements the UpdateWorkoutDto interface.
 */
export function instanceOfUpdateWorkoutDto(value: object): value is UpdateWorkoutDto {
    return true;
}

export function UpdateWorkoutDtoFromJSON(json: any): UpdateWorkoutDto {
    return UpdateWorkoutDtoFromJSONTyped(json, false);
}

export function UpdateWorkoutDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkoutDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(WorkoutBlockDtoFromJSON)),
        'intensity': json['intensity'] == null ? undefined : json['intensity'],
        'status': json['status'] == null ? undefined : json['status'],
        'sportType': json['sportType'] == null ? undefined : json['sportType'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function UpdateWorkoutDtoToJSON(json: any): UpdateWorkoutDto {
    return UpdateWorkoutDtoToJSONTyped(json, false);
}

export function UpdateWorkoutDtoToJSONTyped(value?: UpdateWorkoutDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(WorkoutBlockDtoToJSON)),
        'intensity': value['intensity'],
        'status': value['status'],
        'sportType': value['sportType'],
        'date': value['date'],
    };
}

