/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileDto
 */
export interface UpdateProfileDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    email?: string;
    /**
     * 
     * @type {UpdateProfileDtoRoleEnum}
     * @memberof UpdateProfileDto
     */
    role?: UpdateProfileDtoRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileDto
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileDto
     */
    height?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProfileDto
     */
    goals?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileDto
     */
    availability?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileDto
     */
    password?: string;
}


/**
 * @export
 */
export const UpdateProfileDtoRoleEnum = {
    Standard: 'STANDARD',
    Premium: 'PREMIUM',
    Admin: 'ADMIN'
} as const;
export type UpdateProfileDtoRoleEnum = typeof UpdateProfileDtoRoleEnum[keyof typeof UpdateProfileDtoRoleEnum];


/**
 * Check if a given object implements the UpdateProfileDto interface.
 */
export function instanceOfUpdateProfileDto(value: object): value is UpdateProfileDto {
    return true;
}

export function UpdateProfileDtoFromJSON(json: any): UpdateProfileDto {
    return UpdateProfileDtoFromJSONTyped(json, false);
}

export function UpdateProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : json['dateOfBirth'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'goals': json['goals'] == null ? undefined : json['goals'],
        'availability': json['availability'] == null ? undefined : json['availability'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UpdateProfileDtoToJSON(json: any): UpdateProfileDto {
    return UpdateProfileDtoToJSONTyped(json, false);
}

export function UpdateProfileDtoToJSONTyped(value?: UpdateProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'role': value['role'],
        'dateOfBirth': value['dateOfBirth'],
        'weight': value['weight'],
        'height': value['height'],
        'goals': value['goals'],
        'availability': value['availability'],
        'password': value['password'],
    };
}

