/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWeeklyGoalDto
 */
export interface UpdateWeeklyGoalDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateWeeklyGoalDto
     */
    weekStartDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWeeklyGoalDto
     */
    weekEndDate?: string;
    /**
     * 
     * @type {UpdateWeeklyGoalDtoStatusEnum}
     * @memberof UpdateWeeklyGoalDto
     */
    status?: UpdateWeeklyGoalDtoStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateWeeklyGoalDto
     */
    metrics?: object;
}


/**
 * @export
 */
export const UpdateWeeklyGoalDtoStatusEnum = {
    Planned: 'PLANNED',
    Generated: 'GENERATED',
    Cancelled: 'CANCELLED',
    Locked: 'LOCKED'
} as const;
export type UpdateWeeklyGoalDtoStatusEnum = typeof UpdateWeeklyGoalDtoStatusEnum[keyof typeof UpdateWeeklyGoalDtoStatusEnum];


/**
 * Check if a given object implements the UpdateWeeklyGoalDto interface.
 */
export function instanceOfUpdateWeeklyGoalDto(value: object): value is UpdateWeeklyGoalDto {
    return true;
}

export function UpdateWeeklyGoalDtoFromJSON(json: any): UpdateWeeklyGoalDto {
    return UpdateWeeklyGoalDtoFromJSONTyped(json, false);
}

export function UpdateWeeklyGoalDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWeeklyGoalDto {
    if (json == null) {
        return json;
    }
    return {
        
        'weekStartDate': json['weekStartDate'] == null ? undefined : json['weekStartDate'],
        'weekEndDate': json['weekEndDate'] == null ? undefined : json['weekEndDate'],
        'status': json['status'] == null ? undefined : json['status'],
        'metrics': json['metrics'] == null ? undefined : json['metrics'],
    };
}

export function UpdateWeeklyGoalDtoToJSON(json: any): UpdateWeeklyGoalDto {
    return UpdateWeeklyGoalDtoToJSONTyped(json, false);
}

export function UpdateWeeklyGoalDtoToJSONTyped(value?: UpdateWeeklyGoalDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weekStartDate': value['weekStartDate'],
        'weekEndDate': value['weekEndDate'],
        'status': value['status'],
        'metrics': value['metrics'],
    };
}

