/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTrainingPlanDto
 */
export interface UpdateTrainingPlanDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanDto
     */
    startDate?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateTrainingPlanDto
     */
    weeks?: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanDto
     */
    objective?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTrainingPlanDto
     */
    targetDate?: string;
    /**
     * 
     * @type {Array<UpdateTrainingPlanDtoSportsEnum>}
     * @memberof UpdateTrainingPlanDto
     */
    sports?: Array<UpdateTrainingPlanDtoSportsEnum>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTrainingPlanDto
     */
    autoGenerate?: boolean;
}


/**
 * @export
 */
export const UpdateTrainingPlanDtoSportsEnum = {
    Running: 'running',
    Cycling: 'cycling',
    Swimming: 'swimming',
    Strength: 'strength',
    Crossfit: 'crossfit',
    Triathlon: 'triathlon',
    Duathlon: 'duathlon',
    Yoga: 'yoga',
    Walking: 'walking',
    Other: 'other'
} as const;
export type UpdateTrainingPlanDtoSportsEnum = typeof UpdateTrainingPlanDtoSportsEnum[keyof typeof UpdateTrainingPlanDtoSportsEnum];


/**
 * Check if a given object implements the UpdateTrainingPlanDto interface.
 */
export function instanceOfUpdateTrainingPlanDto(value: object): value is UpdateTrainingPlanDto {
    return true;
}

export function UpdateTrainingPlanDtoFromJSON(json: any): UpdateTrainingPlanDto {
    return UpdateTrainingPlanDtoFromJSONTyped(json, false);
}

export function UpdateTrainingPlanDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTrainingPlanDto {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
        'weeks': json['weeks'] == null ? undefined : json['weeks'],
        'objective': json['objective'] == null ? undefined : json['objective'],
        'targetDate': json['targetDate'] == null ? undefined : json['targetDate'],
        'sports': json['sports'] == null ? undefined : json['sports'],
        'autoGenerate': json['autoGenerate'] == null ? undefined : json['autoGenerate'],
    };
}

export function UpdateTrainingPlanDtoToJSON(json: any): UpdateTrainingPlanDto {
    return UpdateTrainingPlanDtoToJSONTyped(json, false);
}

export function UpdateTrainingPlanDtoToJSONTyped(value?: UpdateTrainingPlanDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'],
        'weeks': value['weeks'],
        'objective': value['objective'],
        'targetDate': value['targetDate'],
        'sports': value['sports'],
        'autoGenerate': value['autoGenerate'],
    };
}

