/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileInput
 */
export interface UpdateProfileInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileInput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileInput
     */
    email?: string;
    /**
     * 
     * @type {object}
     * @memberof UpdateProfileInput
     */
    role?: object;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileInput
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileInput
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileInput
     */
    height?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateProfileInput
     */
    goals?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UpdateProfileInput
     */
    availableDays?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileInput
     */
    password?: string;
}

/**
 * Check if a given object implements the UpdateProfileInput interface.
 */
export function instanceOfUpdateProfileInput(value: object): value is UpdateProfileInput {
    return true;
}

export function UpdateProfileInputFromJSON(json: any): UpdateProfileInput {
    return UpdateProfileInputFromJSONTyped(json, false);
}

export function UpdateProfileInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : json['dateOfBirth'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'goals': json['goals'] == null ? undefined : json['goals'],
        'availableDays': json['availableDays'] == null ? undefined : json['availableDays'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UpdateProfileInputToJSON(json: any): UpdateProfileInput {
    return UpdateProfileInputToJSONTyped(json, false);
}

export function UpdateProfileInputToJSONTyped(value?: UpdateProfileInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'role': value['role'],
        'dateOfBirth': value['dateOfBirth'],
        'weight': value['weight'],
        'height': value['height'],
        'goals': value['goals'],
        'availableDays': value['availableDays'],
        'password': value['password'],
    };
}

