/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserModel
 */
export interface UserModel {
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    email: string;
    /**
     * 
     * @type {UserModelRoleEnum}
     * @memberof UserModel
     */
    role: UserModelRoleEnum;
    /**
     * 
     * @type {Date}
     * @memberof UserModel
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {number}
     * @memberof UserModel
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof UserModel
     */
    height?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserModel
     */
    goals?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof UserModel
     */
    availableDays?: Array<string>;
    /**
     *
     * @type {boolean}
     * @memberof UserModel
     */
    assessmentCompleted?: boolean;
}


/**
 * @export
 */
export const UserModelRoleEnum = {
    Standard: 'STANDARD',
    Premium: 'PREMIUM',
    Admin: 'ADMIN'
} as const;
export type UserModelRoleEnum = typeof UserModelRoleEnum[keyof typeof UserModelRoleEnum];


/**
 * Check if a given object implements the UserModel interface.
 */
export function instanceOfUserModel(value: object): value is UserModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserModelFromJSON(json: any): UserModel {
    return UserModelFromJSONTyped(json, false);
}

export function UserModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'role': json['role'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'weight': json['weight'] == null ? undefined : json['weight'],
        'height': json['height'] == null ? undefined : json['height'],
        'goals': json['goals'] == null ? undefined : json['goals'],
        'availableDays': json['availableDays'] == null ? undefined : json['availableDays'],
        'assessmentCompleted': json['assessmentCompleted'] == null ? undefined : json['assessmentCompleted'],
    };
}

export function UserModelToJSON(json: any): UserModel {
    return UserModelToJSONTyped(json, false);
}

export function UserModelToJSONTyped(value?: UserModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'role': value['role'],
        'dateOfBirth': value['dateOfBirth'] == null ? value['dateOfBirth'] : value['dateOfBirth'].toISOString(),
        'weight': value['weight'],
        'height': value['height'],
        'goals': value['goals'],
        'availableDays': value['availableDays'],
        'assessmentCompleted': value['assessmentCompleted'],
    };
}

