/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkoutBlockDto
 */
export interface WorkoutBlockDto {
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockDto
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof WorkoutBlockDto
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutBlockDto
     */
    distance?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockDto
     */
    targetPace?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutBlockDto
     */
    instructions?: string;
}

/**
 * Check if a given object implements the WorkoutBlockDto interface.
 */
export function instanceOfWorkoutBlockDto(value: object): value is WorkoutBlockDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WorkoutBlockDtoFromJSON(json: any): WorkoutBlockDto {
    return WorkoutBlockDtoFromJSONTyped(json, false);
}

export function WorkoutBlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutBlockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'distance': json['distance'] == null ? undefined : json['distance'],
        'targetPace': json['targetPace'] == null ? undefined : json['targetPace'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
    };
}

export function WorkoutBlockDtoToJSON(json: any): WorkoutBlockDto {
    return WorkoutBlockDtoToJSONTyped(json, false);
}

export function WorkoutBlockDtoToJSONTyped(value?: WorkoutBlockDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'duration': value['duration'],
        'distance': value['distance'],
        'targetPace': value['targetPace'],
        'instructions': value['instructions'],
    };
}

