/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiPlannerResultModel,
  PlanNextWeekDto,
} from '../models/index';
import {
    AiPlannerResultModelFromJSON,
    AiPlannerResultModelToJSON,
    PlanNextWeekDtoFromJSON,
    PlanNextWeekDtoToJSON,
} from '../models/index';

export interface AiPlannerControllerPlanNextWeekRequest {
    planNextWeekDto: PlanNextWeekDto;
}

/**
 * 
 */
export class AiPlannerApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiPlannerControllerPlanNextWeek without sending the request
     */
    async aiPlannerControllerPlanNextWeekRequestOpts(requestParameters: AiPlannerControllerPlanNextWeekRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['planNextWeekDto'] == null) {
            throw new runtime.RequiredError(
                'planNextWeekDto',
                'Required parameter "planNextWeekDto" was null or undefined when calling aiPlannerControllerPlanNextWeek().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ai-planner/plan-next-week`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlanNextWeekDtoToJSON(requestParameters['planNextWeekDto']),
        };
    }

    /**
     */
    async aiPlannerControllerPlanNextWeekRaw(requestParameters: AiPlannerControllerPlanNextWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiPlannerResultModel>> {
        const requestOptions = await this.aiPlannerControllerPlanNextWeekRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiPlannerResultModelFromJSON(jsonValue));
    }

    /**
     */
    async aiPlannerControllerPlanNextWeek(requestParameters: AiPlannerControllerPlanNextWeekRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiPlannerResultModel> {
        const response = await this.aiPlannerControllerPlanNextWeekRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
