/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEquipmentDto,
  UpdateEquipmentDto,
} from '../models/index';
import {
    CreateEquipmentDtoFromJSON,
    CreateEquipmentDtoToJSON,
    UpdateEquipmentDtoFromJSON,
    UpdateEquipmentDtoToJSON,
} from '../models/index';

export interface EquipmentsControllerAddEquipmentToUserRequest {
    equipmentId: string;
}

export interface EquipmentsControllerCreateEquipmentRequest {
    createEquipmentDto: CreateEquipmentDto;
}

export interface EquipmentsControllerDeleteEquipmentRequest {
    uuid: string;
}

export interface EquipmentsControllerGetEquipmentByIdRequest {
    uuid: string;
}

export interface EquipmentsControllerRemoveEquipmentFromUserRequest {
    equipmentId: string;
}

export interface EquipmentsControllerUpdateEquipmentRequest {
    uuid: string;
    updateEquipmentDto: UpdateEquipmentDto;
}

/**
 * 
 */
export class EquipmentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for equipmentsControllerAddEquipmentToUser without sending the request
     */
    async equipmentsControllerAddEquipmentToUserRequestOpts(requestParameters: EquipmentsControllerAddEquipmentToUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['equipmentId'] == null) {
            throw new runtime.RequiredError(
                'equipmentId',
                'Required parameter "equipmentId" was null or undefined when calling equipmentsControllerAddEquipmentToUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments/{equipmentId}/add`;
        urlPath = urlPath.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters['equipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerAddEquipmentToUserRaw(requestParameters: EquipmentsControllerAddEquipmentToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.equipmentsControllerAddEquipmentToUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async equipmentsControllerAddEquipmentToUser(requestParameters: EquipmentsControllerAddEquipmentToUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.equipmentsControllerAddEquipmentToUserRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for equipmentsControllerCreateEquipment without sending the request
     */
    async equipmentsControllerCreateEquipmentRequestOpts(requestParameters: EquipmentsControllerCreateEquipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEquipmentDto'] == null) {
            throw new runtime.RequiredError(
                'createEquipmentDto',
                'Required parameter "createEquipmentDto" was null or undefined when calling equipmentsControllerCreateEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/equipments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEquipmentDtoToJSON(requestParameters['createEquipmentDto']),
        };
    }

    /**
     */
    async equipmentsControllerCreateEquipmentRaw(requestParameters: EquipmentsControllerCreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.equipmentsControllerCreateEquipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async equipmentsControllerCreateEquipment(requestParameters: EquipmentsControllerCreateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.equipmentsControllerCreateEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for equipmentsControllerDeleteEquipment without sending the request
     */
    async equipmentsControllerDeleteEquipmentRequestOpts(requestParameters: EquipmentsControllerDeleteEquipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling equipmentsControllerDeleteEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerDeleteEquipmentRaw(requestParameters: EquipmentsControllerDeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.equipmentsControllerDeleteEquipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async equipmentsControllerDeleteEquipment(requestParameters: EquipmentsControllerDeleteEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.equipmentsControllerDeleteEquipmentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for equipmentsControllerGetAllEquipments without sending the request
     */
    async equipmentsControllerGetAllEquipmentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerGetAllEquipmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const requestOptions = await this.equipmentsControllerGetAllEquipmentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async equipmentsControllerGetAllEquipments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.equipmentsControllerGetAllEquipmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for equipmentsControllerGetEquipmentById without sending the request
     */
    async equipmentsControllerGetEquipmentByIdRequestOpts(requestParameters: EquipmentsControllerGetEquipmentByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling equipmentsControllerGetEquipmentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerGetEquipmentByIdRaw(requestParameters: EquipmentsControllerGetEquipmentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.equipmentsControllerGetEquipmentByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async equipmentsControllerGetEquipmentById(requestParameters: EquipmentsControllerGetEquipmentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.equipmentsControllerGetEquipmentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for equipmentsControllerGetUserEquipments without sending the request
     */
    async equipmentsControllerGetUserEquipmentsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments/my-equipments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerGetUserEquipmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const requestOptions = await this.equipmentsControllerGetUserEquipmentsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async equipmentsControllerGetUserEquipments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.equipmentsControllerGetUserEquipmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for equipmentsControllerRemoveEquipmentFromUser without sending the request
     */
    async equipmentsControllerRemoveEquipmentFromUserRequestOpts(requestParameters: EquipmentsControllerRemoveEquipmentFromUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['equipmentId'] == null) {
            throw new runtime.RequiredError(
                'equipmentId',
                'Required parameter "equipmentId" was null or undefined when calling equipmentsControllerRemoveEquipmentFromUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/equipments/{equipmentId}/remove`;
        urlPath = urlPath.replace(`{${"equipmentId"}}`, encodeURIComponent(String(requestParameters['equipmentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async equipmentsControllerRemoveEquipmentFromUserRaw(requestParameters: EquipmentsControllerRemoveEquipmentFromUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.equipmentsControllerRemoveEquipmentFromUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async equipmentsControllerRemoveEquipmentFromUser(requestParameters: EquipmentsControllerRemoveEquipmentFromUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.equipmentsControllerRemoveEquipmentFromUserRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for equipmentsControllerUpdateEquipment without sending the request
     */
    async equipmentsControllerUpdateEquipmentRequestOpts(requestParameters: EquipmentsControllerUpdateEquipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling equipmentsControllerUpdateEquipment().'
            );
        }

        if (requestParameters['updateEquipmentDto'] == null) {
            throw new runtime.RequiredError(
                'updateEquipmentDto',
                'Required parameter "updateEquipmentDto" was null or undefined when calling equipmentsControllerUpdateEquipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/equipments/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEquipmentDtoToJSON(requestParameters['updateEquipmentDto']),
        };
    }

    /**
     */
    async equipmentsControllerUpdateEquipmentRaw(requestParameters: EquipmentsControllerUpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.equipmentsControllerUpdateEquipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async equipmentsControllerUpdateEquipment(requestParameters: EquipmentsControllerUpdateEquipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.equipmentsControllerUpdateEquipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
