/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthControllerGetStravaAuthUrl200Response,
  IntegrationModel,
  IntegrationsControllerSyncStrava200Response,
  StravaCallbackDto,
} from '../models/index';
import {
    AuthControllerGetStravaAuthUrl200ResponseFromJSON,
    AuthControllerGetStravaAuthUrl200ResponseToJSON,
    IntegrationModelFromJSON,
    IntegrationModelToJSON,
    IntegrationsControllerSyncStrava200ResponseFromJSON,
    IntegrationsControllerSyncStrava200ResponseToJSON,
    StravaCallbackDtoFromJSON,
    StravaCallbackDtoToJSON,
} from '../models/index';

export interface IntegrationsControllerConnectIntegrationRequest {
    integrationId: string;
}

export interface IntegrationsControllerDisconnectIntegrationRequest {
    integrationId: string;
}

export interface IntegrationsControllerHandleStravaCallbackRequest {
    stravaCallbackDto: StravaCallbackDto;
}

/**
 * 
 */
export class IntegrationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for integrationsControllerConnectIntegration without sending the request
     */
    async integrationsControllerConnectIntegrationRequestOpts(requestParameters: IntegrationsControllerConnectIntegrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling integrationsControllerConnectIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/{integrationId}/connect`;
        urlPath = urlPath.replace(`{${"integrationId"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerConnectIntegrationRaw(requestParameters: IntegrationsControllerConnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationModel>> {
        const requestOptions = await this.integrationsControllerConnectIntegrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationModelFromJSON(jsonValue));
    }

    /**
     */
    async integrationsControllerConnectIntegration(requestParameters: IntegrationsControllerConnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationModel> {
        const response = await this.integrationsControllerConnectIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for integrationsControllerDisconnectIntegration without sending the request
     */
    async integrationsControllerDisconnectIntegrationRequestOpts(requestParameters: IntegrationsControllerDisconnectIntegrationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['integrationId'] == null) {
            throw new runtime.RequiredError(
                'integrationId',
                'Required parameter "integrationId" was null or undefined when calling integrationsControllerDisconnectIntegration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/{integrationId}/disconnect`;
        urlPath = urlPath.replace(`{${"integrationId"}}`, encodeURIComponent(String(requestParameters['integrationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerDisconnectIntegrationRaw(requestParameters: IntegrationsControllerDisconnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationModel>> {
        const requestOptions = await this.integrationsControllerDisconnectIntegrationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationModelFromJSON(jsonValue));
    }

    /**
     */
    async integrationsControllerDisconnectIntegration(requestParameters: IntegrationsControllerDisconnectIntegrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationModel> {
        const response = await this.integrationsControllerDisconnectIntegrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for integrationsControllerDisconnectStrava without sending the request
     */
    async integrationsControllerDisconnectStravaRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/strava/disconnect`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerDisconnectStravaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.integrationsControllerDisconnectStravaRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async integrationsControllerDisconnectStrava(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.integrationsControllerDisconnectStravaRaw(initOverrides);
    }

    /**
     * Creates request options for integrationsControllerGetStravaAuthUrl without sending the request
     */
    async integrationsControllerGetStravaAuthUrlRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/strava/auth`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerGetStravaAuthUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthControllerGetStravaAuthUrl200Response>> {
        const requestOptions = await this.integrationsControllerGetStravaAuthUrlRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthControllerGetStravaAuthUrl200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async integrationsControllerGetStravaAuthUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthControllerGetStravaAuthUrl200Response> {
        const response = await this.integrationsControllerGetStravaAuthUrlRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for integrationsControllerHandleStravaCallback without sending the request
     */
    async integrationsControllerHandleStravaCallbackRequestOpts(requestParameters: IntegrationsControllerHandleStravaCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['stravaCallbackDto'] == null) {
            throw new runtime.RequiredError(
                'stravaCallbackDto',
                'Required parameter "stravaCallbackDto" was null or undefined when calling integrationsControllerHandleStravaCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/strava/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StravaCallbackDtoToJSON(requestParameters['stravaCallbackDto']),
        };
    }

    /**
     */
    async integrationsControllerHandleStravaCallbackRaw(requestParameters: IntegrationsControllerHandleStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationModel>> {
        const requestOptions = await this.integrationsControllerHandleStravaCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationModelFromJSON(jsonValue));
    }

    /**
     */
    async integrationsControllerHandleStravaCallback(requestParameters: IntegrationsControllerHandleStravaCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationModel> {
        const response = await this.integrationsControllerHandleStravaCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for integrationsControllerIntegrations without sending the request
     */
    async integrationsControllerIntegrationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerIntegrationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IntegrationModel>>> {
        const requestOptions = await this.integrationsControllerIntegrationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IntegrationModelFromJSON));
    }

    /**
     */
    async integrationsControllerIntegrations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IntegrationModel>> {
        const response = await this.integrationsControllerIntegrationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for integrationsControllerSyncStrava without sending the request
     */
    async integrationsControllerSyncStravaRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/integrations/strava/sync`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async integrationsControllerSyncStravaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IntegrationsControllerSyncStrava200Response>> {
        const requestOptions = await this.integrationsControllerSyncStravaRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IntegrationsControllerSyncStrava200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async integrationsControllerSyncStrava(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IntegrationsControllerSyncStrava200Response | null | undefined > {
        const response = await this.integrationsControllerSyncStravaRaw(initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return null;
            default:
                return await response.value();
        }
    }

}
