/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTrainingPlanDto,
  TrainingPlanModel,
  UpdateTrainingPlanDto,
} from '../models/index';
import {
    CreateTrainingPlanDtoFromJSON,
    CreateTrainingPlanDtoToJSON,
    TrainingPlanModelFromJSON,
    TrainingPlanModelToJSON,
    UpdateTrainingPlanDtoFromJSON,
    UpdateTrainingPlanDtoToJSON,
} from '../models/index';

export interface TrainingPlansControllerCreateTrainingPlanRequest {
    createTrainingPlanDto: CreateTrainingPlanDto;
}

export interface TrainingPlansControllerDeleteTrainingPlanRequest {
    id: string;
}

export interface TrainingPlansControllerGetTrainingPlanByIdRequest {
    id: string;
}

export interface TrainingPlansControllerUpdateTrainingPlanRequest {
    id: string;
    updateTrainingPlanDto: UpdateTrainingPlanDto;
}

/**
 * 
 */
export class TrainingPlansApi extends runtime.BaseAPI {

    /**
     * Creates request options for trainingPlansControllerCreateTrainingPlan without sending the request
     */
    async trainingPlansControllerCreateTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createTrainingPlanDto'] == null) {
            throw new runtime.RequiredError(
                'createTrainingPlanDto',
                'Required parameter "createTrainingPlanDto" was null or undefined when calling trainingPlansControllerCreateTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/training-plans`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTrainingPlanDtoToJSON(requestParameters['createTrainingPlanDto']),
        };
    }

    /**
     */
    async trainingPlansControllerCreateTrainingPlanRaw(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPlanModel>> {
        const requestOptions = await this.trainingPlansControllerCreateTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPlanModelFromJSON(jsonValue));
    }

    /**
     */
    async trainingPlansControllerCreateTrainingPlan(requestParameters: TrainingPlansControllerCreateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPlanModel> {
        const response = await this.trainingPlansControllerCreateTrainingPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for trainingPlansControllerDeleteTrainingPlan without sending the request
     */
    async trainingPlansControllerDeleteTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerDeleteTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerDeleteTrainingPlanRaw(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.trainingPlansControllerDeleteTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async trainingPlansControllerDeleteTrainingPlan(requestParameters: TrainingPlansControllerDeleteTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.trainingPlansControllerDeleteTrainingPlanRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for trainingPlansControllerGetMyTrainingPlan without sending the request
     */
    async trainingPlansControllerGetMyTrainingPlanRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/training-plans/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerGetMyTrainingPlanRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPlanModel>> {
        const requestOptions = await this.trainingPlansControllerGetMyTrainingPlanRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPlanModelFromJSON(jsonValue));
    }

    /**
     */
    async trainingPlansControllerGetMyTrainingPlan(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPlanModel> {
        const response = await this.trainingPlansControllerGetMyTrainingPlanRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for trainingPlansControllerGetTrainingPlanById without sending the request
     */
    async trainingPlansControllerGetTrainingPlanByIdRequestOpts(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerGetTrainingPlanById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async trainingPlansControllerGetTrainingPlanByIdRaw(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPlanModel>> {
        const requestOptions = await this.trainingPlansControllerGetTrainingPlanByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPlanModelFromJSON(jsonValue));
    }

    /**
     */
    async trainingPlansControllerGetTrainingPlanById(requestParameters: TrainingPlansControllerGetTrainingPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPlanModel> {
        const response = await this.trainingPlansControllerGetTrainingPlanByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for trainingPlansControllerUpdateTrainingPlan without sending the request
     */
    async trainingPlansControllerUpdateTrainingPlanRequestOpts(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling trainingPlansControllerUpdateTrainingPlan().'
            );
        }

        if (requestParameters['updateTrainingPlanDto'] == null) {
            throw new runtime.RequiredError(
                'updateTrainingPlanDto',
                'Required parameter "updateTrainingPlanDto" was null or undefined when calling trainingPlansControllerUpdateTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/training-plans/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTrainingPlanDtoToJSON(requestParameters['updateTrainingPlanDto']),
        };
    }

    /**
     */
    async trainingPlansControllerUpdateTrainingPlanRaw(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrainingPlanModel>> {
        const requestOptions = await this.trainingPlansControllerUpdateTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingPlanModelFromJSON(jsonValue));
    }

    /**
     */
    async trainingPlansControllerUpdateTrainingPlan(requestParameters: TrainingPlansControllerUpdateTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrainingPlanModel> {
        const response = await this.trainingPlansControllerUpdateTrainingPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
