/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UpdateProfileDto,
  UserModel,
} from '../models/index';
import {
    UpdateProfileDtoFromJSON,
    UpdateProfileDtoToJSON,
    UserModelFromJSON,
    UserModelToJSON,
} from '../models/index';

export interface UsersControllerUpdateProfileRequest {
    updateProfileDto: UpdateProfileDto;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Creates request options for usersControllerMe without sending the request
     */
    async usersControllerMeRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async usersControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserModel>> {
        const requestOptions = await this.usersControllerMeRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserModelFromJSON(jsonValue));
    }

    /**
     */
    async usersControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserModel> {
        const response = await this.usersControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for usersControllerUpdateProfile without sending the request
     */
    async usersControllerUpdateProfileRequestOpts(requestParameters: UsersControllerUpdateProfileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateProfileDto'] == null) {
            throw new runtime.RequiredError(
                'updateProfileDto',
                'Required parameter "updateProfileDto" was null or undefined when calling usersControllerUpdateProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/profile`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileDtoToJSON(requestParameters['updateProfileDto']),
        };
    }

    /**
     */
    async usersControllerUpdateProfileRaw(requestParameters: UsersControllerUpdateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserModel>> {
        const requestOptions = await this.usersControllerUpdateProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserModelFromJSON(jsonValue));
    }

    /**
     */
    async usersControllerUpdateProfile(requestParameters: UsersControllerUpdateProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserModel> {
        const response = await this.usersControllerUpdateProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
