/* tslint:disable */
/* eslint-disable */
/**
 * IAFit API
 * IAFit Backend API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWorkoutDto,
  SubmitWorkoutFeedbackDto,
  UpdateWorkoutDto,
  WorkoutFeedbackModel,
  WorkoutModel,
} from '../models/index';
import {
    CreateWorkoutDtoFromJSON,
    CreateWorkoutDtoToJSON,
    SubmitWorkoutFeedbackDtoFromJSON,
    SubmitWorkoutFeedbackDtoToJSON,
    UpdateWorkoutDtoFromJSON,
    UpdateWorkoutDtoToJSON,
    WorkoutFeedbackModelFromJSON,
    WorkoutFeedbackModelToJSON,
    WorkoutModelFromJSON,
    WorkoutModelToJSON,
} from '../models/index';

export interface WorkoutsControllerCompleteWorkoutRequest {
    workoutId: string;
}

export interface WorkoutsControllerCreateWorkoutRequest {
    createWorkoutDto: CreateWorkoutDto;
}

export interface WorkoutsControllerSkipWorkoutRequest {
    workoutId: string;
}

export interface WorkoutsControllerSubmitWorkoutFeedbackRequest {
    workoutId: string;
    submitWorkoutFeedbackDto: SubmitWorkoutFeedbackDto;
}

export interface WorkoutsControllerUpdateWorkoutRequest {
    workoutId: string;
    updateWorkoutDto: UpdateWorkoutDto;
}

export interface WorkoutsControllerWorkoutRequest {
    id: string;
}

export interface WorkoutsControllerWorkoutsByTrainingPlanRequest {
    trainingPlanId: string;
}

/**
 * 
 */
export class WorkoutsApi extends runtime.BaseAPI {

    /**
     * Creates request options for workoutsControllerCompleteWorkout without sending the request
     */
    async workoutsControllerCompleteWorkoutRequestOpts(requestParameters: WorkoutsControllerCompleteWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerCompleteWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/{workoutId}/complete`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerCompleteWorkoutRaw(requestParameters: WorkoutsControllerCompleteWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerCompleteWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerCompleteWorkout(requestParameters: WorkoutsControllerCompleteWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerCompleteWorkoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerCreateWorkout without sending the request
     */
    async workoutsControllerCreateWorkoutRequestOpts(requestParameters: WorkoutsControllerCreateWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWorkoutDto'] == null) {
            throw new runtime.RequiredError(
                'createWorkoutDto',
                'Required parameter "createWorkoutDto" was null or undefined when calling workoutsControllerCreateWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkoutDtoToJSON(requestParameters['createWorkoutDto']),
        };
    }

    /**
     */
    async workoutsControllerCreateWorkoutRaw(requestParameters: WorkoutsControllerCreateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerCreateWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerCreateWorkout(requestParameters: WorkoutsControllerCreateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerCreateWorkoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerSkipWorkout without sending the request
     */
    async workoutsControllerSkipWorkoutRequestOpts(requestParameters: WorkoutsControllerSkipWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerSkipWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/{workoutId}/skip`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerSkipWorkoutRaw(requestParameters: WorkoutsControllerSkipWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerSkipWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerSkipWorkout(requestParameters: WorkoutsControllerSkipWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerSkipWorkoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerSubmitWorkoutFeedback without sending the request
     */
    async workoutsControllerSubmitWorkoutFeedbackRequestOpts(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerSubmitWorkoutFeedback().'
            );
        }

        if (requestParameters['submitWorkoutFeedbackDto'] == null) {
            throw new runtime.RequiredError(
                'submitWorkoutFeedbackDto',
                'Required parameter "submitWorkoutFeedbackDto" was null or undefined when calling workoutsControllerSubmitWorkoutFeedback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/{workoutId}/feedback`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitWorkoutFeedbackDtoToJSON(requestParameters['submitWorkoutFeedbackDto']),
        };
    }

    /**
     */
    async workoutsControllerSubmitWorkoutFeedbackRaw(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutFeedbackModel>> {
        const requestOptions = await this.workoutsControllerSubmitWorkoutFeedbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutFeedbackModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerSubmitWorkoutFeedback(requestParameters: WorkoutsControllerSubmitWorkoutFeedbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutFeedbackModel> {
        const response = await this.workoutsControllerSubmitWorkoutFeedbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerTodayWorkout without sending the request
     */
    async workoutsControllerTodayWorkoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/today`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerTodayWorkoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerTodayWorkoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerTodayWorkout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerTodayWorkoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerUpdateWorkout without sending the request
     */
    async workoutsControllerUpdateWorkoutRequestOpts(requestParameters: WorkoutsControllerUpdateWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling workoutsControllerUpdateWorkout().'
            );
        }

        if (requestParameters['updateWorkoutDto'] == null) {
            throw new runtime.RequiredError(
                'updateWorkoutDto',
                'Required parameter "updateWorkoutDto" was null or undefined when calling workoutsControllerUpdateWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/{workoutId}`;
        urlPath = urlPath.replace(`{${"workoutId"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWorkoutDtoToJSON(requestParameters['updateWorkoutDto']),
        };
    }

    /**
     */
    async workoutsControllerUpdateWorkoutRaw(requestParameters: WorkoutsControllerUpdateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerUpdateWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerUpdateWorkout(requestParameters: WorkoutsControllerUpdateWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerUpdateWorkoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerWorkout without sending the request
     */
    async workoutsControllerWorkoutRequestOpts(requestParameters: WorkoutsControllerWorkoutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workoutsControllerWorkout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutRaw(requestParameters: WorkoutsControllerWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkoutModel>> {
        const requestOptions = await this.workoutsControllerWorkoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkoutModelFromJSON(jsonValue));
    }

    /**
     */
    async workoutsControllerWorkout(requestParameters: WorkoutsControllerWorkoutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkoutModel> {
        const response = await this.workoutsControllerWorkoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerWorkoutHistory without sending the request
     */
    async workoutsControllerWorkoutHistoryRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/history`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutHistoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkoutModel>>> {
        const requestOptions = await this.workoutsControllerWorkoutHistoryRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkoutModelFromJSON));
    }

    /**
     */
    async workoutsControllerWorkoutHistory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkoutModel>> {
        const response = await this.workoutsControllerWorkoutHistoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workoutsControllerWorkoutsByTrainingPlan without sending the request
     */
    async workoutsControllerWorkoutsByTrainingPlanRequestOpts(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['trainingPlanId'] == null) {
            throw new runtime.RequiredError(
                'trainingPlanId',
                'Required parameter "trainingPlanId" was null or undefined when calling workoutsControllerWorkoutsByTrainingPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workouts/training-plan/{trainingPlanId}`;
        urlPath = urlPath.replace(`{${"trainingPlanId"}}`, encodeURIComponent(String(requestParameters['trainingPlanId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async workoutsControllerWorkoutsByTrainingPlanRaw(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkoutModel>>> {
        const requestOptions = await this.workoutsControllerWorkoutsByTrainingPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkoutModelFromJSON));
    }

    /**
     */
    async workoutsControllerWorkoutsByTrainingPlan(requestParameters: WorkoutsControllerWorkoutsByTrainingPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkoutModel>> {
        const response = await this.workoutsControllerWorkoutsByTrainingPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
